//gulpApp
export const SIGNED_IN = 'SIGNED_IN';

//Reminder
export const ADD_REMINDER = 'ADD_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const CLEAR_REMINDERS = 'CLEAR_REMINDERS';
export const SORT_REMINDERS = 'SORT_REMINDERS';
export const SORT_REMINDERS_DESC = 'SORT_REMINDERS_DESC';
